version: '3'

services:
  php:
    container_name: "remindme-php"
    build:
      context: .
      args:
        - USER_ID=1000
        - USER=remindme
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/remindme
      - .docker/supervisor/remindme-worker.conf:/etc/supervisor/conf.d/worker.conf
      - .docker/crontab/crontab:/var/spool/cron/crontabs/root
    restart: always
    networks:
      - remindme
    command:
      - /bin/sh
      - -c
      - supervisord -c /etc/supervisor/conf.d/worker.conf
      - supervisorctl start all

  web:
    container_name: "remindme-nginx"
    image: nginx:1.24
    working_dir: /var/www/remindme
    volumes:
      - ./:/var/www/remindme:delegated
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated
    restart: always
    ports:
      - "${WEB_DOCKER_PORT}:80"
    networks:
      - remindme

  db:
    container_name: "remindme-db"
    platform: linux/x86-64
    image: mysql:8
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    restart: always
    volumes:
      - ~/data/db/mysql/remindme:/var/lib/mysql
    ports:
      - "${DB_DOCKER_PORT}:3306"
    networks:
      - remindme
  
  redis:
    container_name: "remindme-redis"
    image: redis:6.2-alpine
    restart: always
    ports:
      - "${REDIS_DOCKER_PORT}:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_DOCKER_PASSWORD}
    volumes:
      - ~/data/db/redis/remindme:/data
    networks:
      - remindme

networks:
  remindme:
    name: remindme
    driver: bridge
