name: Remindme CI/CD

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
    - name: Copy ENV Laravel Configuration for CI
      run: cd src && php -r "file_exists('.env') || copy('.env.ci', '.env');"
    - name: Install Dependencies (PHP Vendors)
      run: cd src && composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: cd src && php artisan key:generate
    - name: Create DB and schemas
      run: |
        cd src && mkdir -p database
        touch database/database.sqlite
        php artisan migrate
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: cd src && vendor/bin/phpunit